### ISSUE TITLE
Typo in CSS class name

### ISSUE THREAD

**Issue by mhilbert** [studer-raimann/UserTakeOver#18]
Typo: Rename CSS class "srag-seach-input" to "srag-search-input".

**Comment by chfsx** [comment]
Sorry, we rarely check the Github repos for reported issues. Usually we deactivate the feature in the repos of our plugins, because the administration of all repos is difficult. Problems with plugins can be reported to support@studer-raimann.ch, where we can also more easily check if there is a maintenance contract/SLA for the plugin.

We will fix this small issue in a future version.
