### ISSUE TITLE
Configuration not working with ILIAS 5.2

### ISSUE THREAD

**Issue by dymitar** [studer-raimann/UserTakeOver#22]
Hi,
The configuration is not working with ILIAS 5.2.20 (PHP 5.6).
It crashes with Class 'ilObjectPluginAccess' not found in /..../Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/UserTakeOver/classes/Access/class.ilObjUserTakeOverAccess.php:11

Adding an entry to the classmap of the autoloader solves this problem, but there is another one:
Call to undefined method ilToolbarGUI::addComponent() in /..../Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/UserTakeOver/classes/Groups/class.ilUserTakeOverGroupsGUI.php:87

The plugin itself is working and the switching of the user is OK.

The configuration is working with ILIAS 5.3

**Comment by chfsx** [comment]
Hi @dymitar 

Sorry, we rarely check the Github repos for reported issues. Usually we deactivate the feature in the repos of our plugins, because the administration of all repos is difficult. Problems with plugins can be reported to support@studer-raimann.ch, where we can also more easily check if there is a maintenance contract/SLA for the plugin.

We're sorry that you had to wait so long. Especially because the ILIAS version in which the problem occurred is no longer supported in the meantime. Could you already switch to a newer ILIAS version and install a new version of the plugin where the problem no longer occurs?
